### ISSUE TITLE
installation process of dtb

### ISSUE THREAD

**Issue by sani1486** [InES-HPMM/linux-l4t-4.4#1]
well , I tried it just now . but I have some queries on L4t 28.1 ,I didn't understand the installation process clearly . 
1. should i need to compile the kernel ? or should i just need to compile the dtbs doing only "make dtbs" .

2. And how do i exactly replace the dtbs from `linux-l4t-4.4/kernel/kernel-4.4/arch/arm64/boot/dts` folder i can see there are total 8 dtb files and among them both `tegra210-jetson-tx1-p2597-2180-a01-devkit-hdmi2csi.dtb` and `tegra210-jetson-tx1-p2597-2180-a01-devkit.dtb` exist . but in `64_TX1/Linux_for_Tegra_64_tx1/kernel/dtb` folder.  I saw 3 dtbs , these three have their counterparts in the` linux-l4t-4.4/kernel/kernel-4.4/arch/arm64/boot/dts` folder with the same name too, but sizes are different . so what should be the right way to replace them , replace only the `tegra210-jetson-tx1-p2597-2180-a01-devkit-hdmi2csi.dtb` or put all of them in the jetpack's dtb folder ? or just remove the `tegra210-jetson-tx1-p2597-2180-a01-devkit.dtb` file and then paste the` tegra210-jetson-tx1-p2597-2180-a01-devkit-hdmi2csi.dtb` file ? or should i rename `tegra210-jetson-tx1-p2597-2180-a01-devkit-hdmi2csi.dtb` file to `tegra210-jetson-tx1-p2597-2180-a01-devkit.dtb`
3. should i also replace the `Image` and `zImage` and `dtc` files?
4. I tried `sudo ./flash -r -k DTB jetson-tx1 mmcblk0p1` this command and it says it's looking for `tegra210-jetson-tx1-p2597-2180-a01-devkit.dtb` but i actually deleted it and placed  `tegra210-jetson-tx1-p2597-2180-a01-devkit-hdmi2csi.dtb`

Please Advise 
Regards

**Comment by matthiasFrei** [comment]
RTFM!

All your questions are answered in our Kernel compilation guide,
https://github.com/InES-HPMM/linux-l4t-4.4/wiki/customKernelCompilation
please read the guide more carefully and follow the given instructions

1: https://github.com/InES-HPMM/linux-l4t-4.4/wiki/customKernelCompilation#custom-kernel-compilation
2: https://github.com/InES-HPMM/linux-l4t-4.4/wiki/customKernelCompilation#device-tree
3: https://github.com/InES-HPMM/linux-l4t-4.4/wiki/customKernelCompilation#replace--install-new-kernel-files
4: https://github.com/InES-HPMM/linux-l4t-4.4/wiki/customKernelCompilation#device-tree

**Comment by sani1486** [comment]
Thanks , I successfully flashed everything . But still trying to figure out the exact way to change the dtb to disable the hdmi in B .
