### ISSUE TITLE
How to use HDCP support

### ISSUE THREAD

**Issue by searler** [InES-HPMM/linux-l4t-4.4#10]

**Comment by searler** [comment]
The documentation for the HDMI2CSI indicates that HDCP 1.4 is supported.

The driver documentation that I have found indicates that HDCP is not yet supported by the software.

What is the current position?

**Comment by dariis** [comment]
It is not planned to expand the driver.

Additionally we do not have the possibility to test, because HDCP is optional in the Toshiba chip and we do not use chips with the encryption option.

**Comment by searler** [comment]
Thank you
