### ISSUE TITLE
Support for R32.1

### ISSUE THREAD

**Issue by mstallmo** [InES-HPMM/linux-l4t-4.4#11]
Hi,

Forgive me if this is kind of a stupid question but I am hoping to update the drivers you all have written here to the newest version of L4T (R32.1). I was wondering if you all would be able to point me in the direction of what would need to be changed to run it with this newest release?

Thank you in advance!

**Comment by dariis** [comment]
We did not investigate the changes from 28.2.1 to 32.1 (yet), because it is not planed to update the the driver.

A starting point could be the tegra camera platform. To name some files:
`channel.c`, `csi4_fops.c`, `vi4_fops.c`, ...
