### ISSUE TITLE
Device tree documentation for AGX Xavier

### ISSUE THREAD

**Issue by mstallmo** [InES-HPMM/linux-l4t-4.4#12]
I have the adapter board pictured here: https://github.com/InES-HPMM/linux-l4t-4.4/issues/8 to fit the connector on the AGX Xavier board. I was wondering where I could find documentation on the needed changes to make the device tree to work with the Xavier?

**Comment by dariis** [comment]
If we have time we try to adapt the driver (device tree) for L4T 32.1. But the adapter board is not from us, so we can not give you support on that at the moment.
