### ISSUE TITLE
Driver for jetpack 4.2.1 

### ISSUE THREAD

**Issue by sani1486** [InES-HPMM/linux-l4t-4.4#13]
Thanks for this  driver . 
If there is any possibility to update this driver for the jetpack 4.2.1 with their latest kernel version ? or  any timetable when it May be updated ?

**Comment by dariis** [comment]
It is not officially planed to support the latest kernel version, but we try to adapt it if we have free human resources. If we have a running version we will publish it.

**Comment by sani1486** [comment]
Thanks.
I believe many of us are eagerly waiting

**Comment by weissric** [comment]
We have now updated our driver to version l4t-r32.2.1. This version corresponds to the one that comes with Jetpack 4.2.2. The driver can be found in the [linux-l4t-4.9](https://github.com/InES-HPMM/linux-l4t-4.9.git) repository.

**Comment by sani1486** [comment]
Thank you so very much

    On Thursday, September 26, 2019, 10:46:18 PM GMT+9, weissric <notifications@github.com> wrote:  
 
 
We have now updated our driver to version l4t-r32.2.1. This version corresponds to the one that comes with Jetpack 4.2.2. The driver can be found in the linux-l4t-4.9 repository.
