### ISSUE TITLE
make tegra18_hdmi2csi_defconfig error

### ISSUE THREAD

**Issue by fhqddm** [InES-HPMM/linux-l4t-4.4#15]
I tried many times, but failed to compile on 32.2.1, so I dropped to 28.2.1. follow the steps:
clone the whole repository  and check out:
 74987ea47a13e9ef046c3bb6500a45852fede114 hardware/nvidia/platform/t18x/common (tegra-l4t-r28.1)
 67b165cf14e6a34ce3113ce41715fec688dd794c hardware/nvidia/platform/t18x/quill (heads/hdmi2csi/l4t-r28.1)
 0e4ac7bff000c458005bf532cc5bd58fbbed62b4 hardware/nvidia/platform/t210/common (tegra-l4t-r28.1)
 d82ec996b2fbf97894721adf84d5488e1c08e48a hardware/nvidia/platform/t210/jetson (heads/hdmi2csi/l4t-r28.1)
 53ff710dd05783e6ef444c545eee112dccda1fe5 hardware/nvidia/platform/tegra/common (tegra-l4t-r28.1)
 412bb1bbb48945eed61f31accf83116ee3320dc7 hardware/nvidia/soc/t18x (tegra-l4t-r28.1)
 ee8b9d78b2091deeead9e0a2c7282b3cdb47e2e7 hardware/nvidia/soc/t210 (tegra-l4t-r28.1)
 4bcf1deb457958585c79a894957823e3617c7777 hardware/nvidia/soc/tegra (tegra-l4t-r28.1)
 1bba0f819ede9a224141f9daae4300add35fbd03 kernel/display (tegra-l4t-r28.1)
 878fbe7ba0789f2cbc0192fa53fd9b5d37ad342a kernel/kernel-4.4 (heads/hdmi2csi/l4t-r28.1)
 c33aefb7c596874ee7ba31b0fb7dca3c6df19e7b kernel/nvgpu (heads/hdmi2csi/l4t-r28.1)
 e62d00b7e110bc82b7eed3dd6faa1b48fadae435 kernel/nvhost (tegra-l4t-r28.1)
 fc9b7fa02156503ada6fff3d71d388ca521d1130 kernel/nvmap (tegra-l4t-r28.3.1)
 6b18b31b44f34cf4d8a65217c7773e965082db9b kernel/nvmap-t18x (tegra-l4t-r28.3.1)
 8b76f7fc8fbdba75bf6f784634374e65a05d3314 kernel/t18x (tegra-l4t-r28.1)

export ARCH=arm64
export CROSS_COMPILE=/usr/bin/aarch64-linux-gnu-

make tegra18_hdmi2csi_defconfig:
error message show a lot of  "syntax error":
'ernel/trace/Kconfig:405⚠️ ignoring unsupported character '
kernel/trace/Kconfig:405: unknown option "This"
kernel/trace/Kconfig:406⚠️ ignoring unsupported character ','
'ernel/trace/Kconfig:406⚠️ ignoring unsupported character '
kernel/trace/Kconfig:406: unknown option "kernel"
'ernel/trace/Kconfig:407⚠️ ignoring unsupported character '
kernel/trace/Kconfig:407: unknown option "stack-trace"
'ernel/trace/Kconfig:408⚠️ ignoring unsupported character '
kernel/trace/Kconfig:408: unknown option "then"
'ernel/trace/Kconfig:409⚠️ ignoring unsupported character '
kernel/trace/Kconfig:409: unknown option "is"

**Comment by weissric** [comment]
What host machine are you using?
`uname -a`

**Comment by fhqddm** [comment]
Linux zs 4.15.0-70-generic #79~16.04.1-Ubuntu SMP Tue Nov 12 14:01:10 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by fhqddm** [comment]
Could you please leave an email or skype so that we can communicate in detail
