### ISSUE TITLE
HDMI-In does not work(there`s no /dev/video0(or 1)

### ISSUE THREAD

**Issue by aprentis** [InES-HPMM/linux-l4t-4.4#4]
Hi! 

I've fl'shed my Jetson TX1 with linux-l4t-4.4 core from this repo and placed it on auvidea J130-4K board. 

When i've tried 
`ubuntu@tegra-ubuntu:~$ modprobe tc358840`
`modprobe: FATAL: Module tc358840 not found in directory /lib/modules/4.4.38-tegra` 
 
then i had a look into dev. 
`ubuntu@tegra-ubuntu:~$ ls /dev/v*
/dev/v4l-subdev0  /dev/vcs1  /dev/vcs4  /dev/vcs7   /dev/vcsa2  /dev/vcsa5
/dev/v4l-subdev1  /dev/vcs2  /dev/vcs5  /dev/vcsa   /dev/vcsa3  /dev/vcsa6
/dev/vcs          /dev/vcs3  /dev/vcs6  /dev/vcsa1  /dev/vcsa4  /dev/vcsa7
`

What`s wrong? How could i use HDMI-In on this board? 
Thank you in advance

**Comment by tkammacher** [comment]
Hi
As stated in the Wiki https://github.com/InES-HPMM/linux-l4t-4.4/wiki/hdmi2csi, our linux-l4t-4.4 repository supports the HDMI2CSI board when plugged into the TX1/TX2 base board. It does not support the auvidea J130 base board.

If you need the up-to-date linux-l4t-4.4 (for L4T 28.1) on the auvidea J130, then someone would have to port it to this base board first. Actually the hardware is not that different, but they use different CSI lanes, so at least the device tree would need some changes. We have no plans to do this in the near future.

Back in summer 2017 we ported the older linux-l4t (https://github.com/InES-HPMM/linux-l4t) to the auvidea J130 (TX1 only). But note, that this version is based on the old L4T 24.2.1, so if you wanted to use that you would have to flash your TX1 with 24.2.1 first. 
More information on building is in the Wiki: https://github.com/InES-HPMM/linux-l4t/wiki/auvideaJ130 and https://github.com/InES-HPMM/linux-l4t/wiki/hdmi2csi


Then looking at the modprobe error you posted, it looks like there is a mismatch between the kernel modules you built and the Linux version currently running (`4.4.38-tegra`). But the drivers wouldn't work on the J130 anyway, as explained above..

**Comment by aprentis** [comment]
@tkammacher Thank you for your reply! 

I've tried this old linux-l4t (https://github.com/InES-HPMM/linux-l4t) recently. I've used prebuilt image, flashed my TX1 with it, but after reboot it got stuck. I`ve tried both Developer board and J130. 
Should i built this kernel myself?

**Comment by aprentis** [comment]
Actually, when i flashed it with old kernel using this manual(https://github.com/InES-HPMM/linux-l4t/wiki/customKernelCompilation), i've got this 

`  0.000000] Preemptible hierarchical RCU implementation.

[    0.000000]  RCU restricting CPUs from NR_CPUS=8 to nr_cpu_ids=4.
[    0.000000] NR_IRQS:704 nr_irqs:704 0
[    0.000000] of_irq_init: children remain, but no parents
[    0.000000] Architected local timer running at 19.20MHz (phys).
[    0.000000] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 3579139424256ns
[    0.000000] irq: no irq domain found for /interrupt-controller@60004000 !
[    0.000000] tegra210_timer_init: can't map IRQ for CPU0
[    0.000000] BUG: failure at drivers/clocksource/tegra210_timer.c:215/tegra210_timer_init()!
[    0.000000] Enter nvdumper_crash_setup_regs
[    0.000000] nvdumper_cpu_data is not initialized!
[    0.000000] Kernel panic - not syncing: BUG!
[    0.000000] CPU: 0 PID: 0 Comm: swapper/0 Tainted: G        W    3.10.96 #1
[    0.000000] Call trace:
[    0.000000] [<ffffffc000089b98>] dump_backtrace+0x0/0xf4
  0.000000] Preemptible hierarchical RCU implementation.
[    0.000000]  RCU restricting CPUs from NR_CPUS=8 to nr_cpu_ids=4.
[    0.000000] NR_IRQS:704 nr_irqs:704 0
[    0.000000] of_irq_init: children remain, but no parents
[    0.000000] Architected local timer running at 19.20MHz (phys).
[    0.000000] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 3579139424256ns
[    0.000000] irq: no irq domain found for /interrupt-controller@60004000 !
[    0.000000] tegra210_timer_init: can't map IRQ for CPU0
[    0.000000] BUG: failure at drivers/clocksource/tegra210_timer.c:215/tegra210_timer_init()!
[    0.000000] Enter nvdumper_crash_setup_regs
[    0.000000] nvdumper_cpu_data is not initialized!
[    0.000000] Kernel panic - not syncing: BUG!
[    0.000000] CPU: 0 PID: 0 Comm: swapper/0 Tainted: G        W    3.10.96 #1
[    0.000000] Call trace:
[    0.000000] [<ffffffc000089b98>] dump_backtrace+0x0/0xf4

`

**Comment by matthiasFrei** [comment]
Hi,
As written here:(https://github.com/InES-HPMM/linux-l4t/wiki/auvideaJ130) for the Auvidea J130 Board there is no prebuilt image. 

In order to get the J130 working you need to do the following steps:
 * flash your TX1 with 24.2.1. using jetpack
 * Modify your J130 as shown here: https://github.com/InES-HPMM/linux-l4t/wiki/auvideaJ130#enable-interrupt-for-input-j17-hdmi-2
 * Building the Kernel: 
   * make sure you checked out the correct branch:[l4t-r24-2.1-auvideaj130](https://github.com/InES-HPMM/linux-l4t/tree/hdmi2csi/l4t-r24-2.1-auvideaj130)
   * load the defconfig
   * build the kernel, modules and dtb
* copy the kernel and dtb to your Target(Tx1) and install the modules
* change the extlinux.conf file if necessary
