### ISSUE TITLE
Audio is just static...

### ISSUE THREAD

**Issue by MTNTheCompWiz** [InES-HPMM/linux-l4t-4.4#5]
I know the wiki says audio is untested... so I thought I would give it a try.  Long story short, audio is being sent to j21's i2s bus... but either the codec is wrong or something else, because all I get is static (except when the input source is silent).  Unfortunately, I'm not too sure how to troubleshoot this.  Any pointers?

**Comment by tkammacher** [comment]
Hi, yes Audio is untested on the linux-l4t-4.4 version of our drivers. Unfortunately we have currently not planned to support audio, as we do not need it in any of our projects.
The way to capture audio on our old linux-l4t (based on kernel version 3.10) on I2S4 is described here: [1].
If you want to look at enabling audio capture, maybe it helps to look at our old commits related to enabling audio: [2]
Actually my guess is, that there might be issues here:
* Some configuration might not yet be enabled in the tc358840.c driver for the HDMI-to-CSI conversion IC (compare to [3])
* The device tree is most probably missing something.. compare to [2]
* Some setting in alsamixer might prevent you from getting an input.. there are just so many possible settings there, it's rather convoluted
* Maybe something in the underlying audio architecture has changed between kernel 3.10 and 4.4 .. we have not looked into that at all

Hope that helps.. 

[1]
https://github.com/InES-HPMM/linux-l4t/wiki/captureHdmiAudio
[2]
https://github.com/InES-HPMM/linux-l4t/commit/9150157d2b1f73aefe01e9a07e3b062a45d57247
[3]
https://github.com/InES-HPMM/linux-l4t/blob/hdmi2csi/l4t-r24-2.1/drivers/media/i2c/tc358840.c
