### ISSUE TITLE
Jetpack 3.2/R28.2

### ISSUE THREAD

**Issue by goetzdd** [InES-HPMM/linux-l4t-4.4#6]
Is there a plan to release a newer version compatible with Jetpack 3.2/R28.2? R28.1 and R28.2 are not far apart, but a quick diff of the current repository version vs nvidia R28.2 appears to show more diffs than I'd expect. Or there are more changes than I expect.

**Comment by tkammacher** [comment]
Released today: https://github.com/InES-HPMM/linux-l4t-4.4/releases/tag/l4t-r28.2.1
