### ISSUE TITLE
[Request] Support for AGX Xavier

### ISSUE THREAD

**Issue by alxbouchard** [InES-HPMM/linux-l4t-4.4#8]
Just got the HDMI2CSI_Xavier Adapter and I'm wondering if there's any timeline for supporting the new AGX Xavier?

**Comment by dariis** [comment]
Sorry for the late response, we had some staff turnover.

It is not planed to support the Xavier because this would need a hardware change of the HDMI to CSI board.

**Comment by alxbouchard** [comment]
Thanks for the reply. Pender now make an HDMI2CSI Xavier Adapter:
![img_4779](https://user-images.githubusercontent.com/21181350/52757515-e4d03a00-2fd2-11e9-9ae4-b00876a5b31d.jpg)
![image_small](https://user-images.githubusercontent.com/21181350/52757516-e4d03a00-2fd2-11e9-8f98-493ea652cf66.jpg)
