### ISSUE TITLE
New TX1 vs Old TX1

### ISSUE THREAD

**Issue by MTNTheCompWiz** [InES-HPMM/linux-l4t-4.4#9]
I purchased quite a large number of TX1s and HDMI2CSI boards, and have run into a big problem.  On my new boards, the driver pukes when trying to load the driver (specifically when the 2nd chip is initialized.  (the one on 7h1f.  The 7h0f seems to load fine.)

Has anyone else encountered this (or know of a fix?)?

**Comment by MTNTheCompWiz** [comment]
Just to make sure everything on my build was clean... I wiped all my local copies of repos, did a fresh full flash using jetpack 3.2 on a brand-new board, then rebuilt everything following the instructions to the letter, and I still the system dying after a few minutes, and no video0/1 devices loaded.


In dmesg, I get the following:

[  315.056697] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[ 1161.603307] bpmp_wait_ack() returned -110 on ch 0
[ 1161.608194] mrq 2 data [0x0 0x0 0x0 0x0 0xe 0x0 0x0 0x0 0x11 0x0 0x0 0x0 ]
[ 1161.616068] ------------[ cut here ]------------
[ 1161.620756] WARNING: at drivers/firmware/tegra/mail.c:357
[ 1161.626204] Modules linked in: bcmdhd bluedroid_pm
[ 1161.631203] 
[ 1161.632792] CPU: 0 PID: 0 Comm: swapper/0 Not tainted 4.4.38+ #1
[ 1161.638857] Hardware name: jetson_tx1 (DT)
[ 1161.643028] task: ffffffc0012c9ac0 ti: ffffffc0012b4000 task.ti: ffffffc0012b4000
[ 1161.650647] PC is at tegra_bpmp_send_receive_atomic+0xe4/0x138
[ 1161.656548] LR is at tegra_bpmp_send_receive_atomic+0xe4/0x138
[ 1161.662439] pc : [<ffffffc00083e124>] lr : [<ffffffc00083e124>] pstate: 800001c5
[ 1161.669878] sp : ffffffc0012b7d50
[ 1161.673250] x29: ffffffc0012b7d50 x28: 0000000000000000 
[ 1161.678709] x27: ffffffc0000801d8 x26: 000000008151c000 
[ 1161.684157] x25: 00000000ffffff92 x24: 0000000000000002 
[ 1161.689605] x23: ffffffc0012b7db0 x22: 0000000000000004 
[ 1161.695050] x21: ffffffc0012b7db8 x20: 000000000000000c 
[ 1161.700490] x19: 0000000000000000 x18: 0000000000000000 
[ 1161.705935] x17: 0000000000000000 x16: 0000000000000000 
[ 1161.711377] x15: 0000000000000000 x14: 0000000000000000 
[ 1161.716814] x13: 0000000000000000 x12: 0000000000000000 
[ 1161.722253] x11: 0000000000000000 x10: 0000000000000000 
[ 1161.727697] x9 : 0000000000000000 x8 : ffffffc0002f061c 
[ 1161.733141] x7 : 0000000000000000 x6 : 0000000000000002 
[ 1161.738580] x5 : 0000000000000001 x4 : ffffffc0012b7b30 
[ 1161.744020] x3 : 0000000000000007 x2 : 0000000000000000 
[ 1161.749461] x1 : 0000000000000002 x0 : 0000000000000001 
[ 1161.754897] 
[ 1161.756451] ---[ end trace fad8db5dce6a6b41 ]---
[ 1161.761125] Call trace:
[ 1161.763658] [<ffffffc00083e124>] tegra_bpmp_send_receive_atomic+0xe4/0x138
[ 1161.770626] [<ffffffc000510cb4>] tegra_bpmp_do_idle+0x2c/0x40
[ 1161.776448] [<ffffffc000510d30>] proc_idle_state_enter+0x68/0x140
[ 1161.782612] [<ffffffc000510e34>] tegra210_cpu_pm_notifier+0x2c/0x58
[ 1161.788961] [<ffffffc0000c45cc>] notifier_call_chain+0x44/0x84
[ 1161.794874] [<ffffffc0000c4640>] __raw_notifier_call_chain+0xc/0x14
[ 1161.801215] [<ffffffc0005103c0>] tegra210_cpu_pm_notify+0x2c/0x50
[ 1161.807377] [<ffffffc00051041c>] tegra210_cpu_pm_enter+0x38/0x54
[ 1161.813460] [<ffffffc00081536c>] arm_enter_idle_state+0x44/0x8c
[ 1161.819466] [<ffffffc0008132c8>] cpuidle_enter_state+0x168/0x2f8
[ 1161.825545] [<ffffffc000813490>] cpuidle_enter+0x18/0x20
[ 1161.830939] [<ffffffc0000e6758>] call_cpuidle+0x4c/0x58
[ 1161.836243] [<ffffffc0000e6830>] cpuidle_idle_call+0xcc/0x120
[ 1161.842066] [<ffffffc0000e6ae0>] cpu_idle_loop+0x25c/0x27c
[ 1161.847633] [<ffffffc0000e6b10>] convert_prio+0x0/0x3c
[ 1161.852852] [<ffffffc000b36144>] rest_init+0x8c/0x98
[ 1161.857899] [<ffffffc00116aa7c>] start_kernel+0x2dc/0x2e4
[ 1161.863360] [<0000000080b3c000>] 0x80b3c000

and from that point on, the entire system seems to lag in response.  Nothing shows in top... so not sure exactly what is lagging.

So, what gives?   Is this driver even being maintained anymore?

**Comment by dariis** [comment]
Sorry for the late response, we had some staff turnover.

I do not see the link to our driver in the call trace.
Just to make sure, we only tested the TX1 on l4t 28.1 not 28.2.1.
